<?php $displayName = $this->zfcUserDisplayName(); ?>
<div class="pull-right">
    <div class="navbar-collapse">
        <ul class="nav navbar-nav">
           <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $displayName; ?> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="<?php echo $this->url('zfcuser/logout') ?>">Logout</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>

<div class="navbar-collapse settings">
    <ul class="nav navbar-nav">
        <?php foreach ($this->container as $page) :?>
            <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
            <?php // when using partials we need to manually check for ACL conditions ?>
            <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) :
                continue;
            endif; ?>
            <?php $hasChildren = $page->hasPages(); ?>
            <?php if (!$hasChildren) : ?>
                <li <?php if ($page->isActive()) echo 'class="active"'; ?>>
                    <a href="<?php echo $page->getHref() ?>">
                        <span class="icon icon-wrench icon-white"></span>
                        <?php //echo $this->translate($page->getLabel()) ?>
                    </a>
                </li>
            <?php else : ?>
                <li class="dropdown
                    <?php foreach ($page->getPages() as $child) :
                        if ($child->isActive()) echo ' active';
                    endforeach;
                    ?>">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <span class="icon icon-wrench icon-white"></span>
                    <?php //echo $this->translate($page->getLabel()) ?> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <?php foreach ($page->getPages() as $child) : ?>
                        <?php // when using partials we need to manually check for ACL conditions ?>
                        <?php if(!$child->isVisible() || !$this->navigation()->accept($child)) :
                            continue;
                        endif; ?>
                        <li <?php if ($child->isActive()) echo 'class="active"'; ?>>
                            <a href="<?php echo $child->getHref() ?>">
                                <?php echo $this->translate($child->getLabel()) ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</div>




