<div class="container">

    <?php echo $this->flashMessenger()->render(); ?>
    <h1 class="page-header" >List not approved news</h1>
    <a class="btn btn-success" href="<?php echo $this->url('addNews'); ?>">
        <i class="icon-plus icon-white"></i> Add news
    </a>
    
    <br/><br/>

    <table class="table table-striped table-bordered table-sortable">
        <thead>
            <tr>
                <th>Image</th>
                <th>Title</th>
                <th>Description</th>
                <th class="filter-false sorter-false">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->news as $news) : ?>
                <tr>
                    <td><img src="<?php echo $this->imagesUrl . $news['image'] ?>" width="200"/></td>
                    <td><?php echo $news['title']; ?></td>
                    <td><?php echo $news['description']; ?></td>
                    <td>
                        <div>
                            <a class="btn btn-info" href="<?php echo $this->url('approveNews', array('id' => $news['id'])); ?>"><i class="icon-edit icon-white"></i> approve</a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>


</div>
