<div class="container">

    <?php echo $this->flashMessenger()->render(); ?>
    <h1 class="page-header" >List News</h1>
    <a class="btn btn-success" href="<?php echo $this->url('addNews'); ?>">
        <i class="icon-plus icon-white"></i> Add news
    </a>
    
    <hr />

    <table class="table table-striped table-bordered table-sortable">
        <thead>
            <tr>
                <th>Image</th>
                <th>Title</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->news as $news) : ?>
                <tr>
                    <td><img src="<?php echo $this->imagesUrl . $news['image'] ?>" width="200"/></td>
                    <td><?php echo $news['title']; ?></td>
                    <td><?php echo $news['description']; ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>
