<div class="container">

    <?php echo $this->flashMessenger()->render(); ?>

    <h1 class="page-header" >List users</h1>

    <br/><br/>

    <table class="table table-striped table-bordered table-sortable">
        <thead>
            <tr>
                <th>ID</th>
                <th>E-mail</th>
                <th>Role</th>
                <th class="filter-false sorter-false">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user) : ?>
                <tr>
                    <td><?php echo $user['user_id'] ?></td>
                    <td><a href="<?php echo $this->url('editUser', array('id' => $user['user_id'])); ?>"><?php echo $user['email']; ?></a></td>
                    <td><a href="<?php echo $this->url('editUser', array('id' => $user['user_id'])); ?>"><?php echo $user['role_id']; ?></a></td>
                    <td>
                        <div>
                            <a class="btn btn-info" href="<?php echo $this->url('editUser', array('id' => $user['user_id'])); ?>"><i class="icon-edit icon-white"></i> edit role</a>
                            <a class="btn btn-info" href="<?php echo $this->url('userPermissions', array('id' => $user['user_id'])); ?>"><i class="icon-edit icon-white"></i> user permissions</a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>
