<div class="container">

    <?php echo $this->flashMessenger()->render(); ?>

    <h1 class="page-header" >Role permission <sup><span class="label label-info"><?php echo $role; ?></span></sup></h1>

    <br/>

    <?php
    $form->prepare();
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    $checkbox = new Zend\Form\Element\Checkbox('check-all');
    $checkbox->setUseHiddenElement(false);
    ?>

    <table class="table table-striped table-bordered table-sortable" id ="permission">
        <thead>
            <tr>
                <th style="width: 20px;" class="filter-false sorter-false"><?php echo $this->formRow($checkbox); ?></th>
                <th>Resource</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($allResources as $key => $resource) : ?>
                <tr>
                    <td><input type="checkbox" name="<?php echo 'resource[' . $resource['id'] . ']'; ?>" value="<?php echo $resource['id']; ?>" <?php if (in_array($resource['resource'], $permissions)) echo 'checked="checked"'; ?>/></td>
                    <td><?php echo $resource['resource']; ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php echo $this->formRow($form->get('save')->setAttribute('class', 'btn btn-danger')); ?>

    <?php echo $this->form()->closeTag(); ?>
</div>

<script type="text/javascript">

    $(document).ready(function() {

        $('#permission input[name="check-all"]').on('change', function(e) {
            $.each($('#permission input[type="checkbox"]'), function(key, inputElement) {
                $(inputElement).prop('checked', e.target.checked);
            });
        });

    });
</script>
