<div class="container">

    <?php echo $this->flashMessenger()->render(); ?>

    <h1 class="page-header" >List roles</h1>
    <br/>
    <!--<div class="form-actions">-->
        <a class="btn btn-success" href="<?php echo $this->url('addRole'); ?>"><i class="icon-plus icon-white"></i> Add role</a>
    <!--</div>-->

    <br/><br/>

    <table class="table table-striped table-bordered table-sortable">
        <thead>
            <tr>
                <th>Role</th>
                <th class="filter-false sorter-false">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($roles as $role) : ?>
                <tr>
                    <td><a href="<?php echo $this->url('editRole', array('id' => $role['id'])); ?>"><?php echo $role['role_id']; ?></a></td>
                    <td>
                        <div>
                            <a class="btn btn-info" href="<?php echo $this->url('editRole', array('id' => $role['id'])); ?>"><i class="icon-edit icon-white"></i> edit</a>
                            <a class="btn btn-info" href="<?php echo $this->url('rolePermissions', array('id' => $role['id'])); ?>"><i class="icon-edit icon-white"></i> permissions</a>
                            <span class="deleteButton">
                                <a class="btn btn-danger" href="<?php echo $this->url('deleteRole', array('id' => $role['id'])); ?>"  ><i class="icon-remove icon-white"></i> delete</a>
                            </span>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true" style="display: none; height: 170px;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Delete role</h4>
      </div>
      <div class="modal-body">
          Are you sure you want to delete role ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a class="btn btn-danger" href=""><i class="icon-remove icon-white"></i> delete</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
