<div class="container">

    <?php echo $this->flashMessenger()->render(); ?>

    <h1 class="page-header" >List resources</h1>

    <br/>

    <table class="table table-striped table-bordered table-sortable">
        <thead>
            <tr>
                <th>Resource</th>
                <th class="filter-false sorter-false">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($resources as $resource) : ?>
                <tr>
                    <td><?php echo $resource['resource']; ?></td>
                    <td>
                        <div>
                            <span class="deleteButton">
                                <a class="btn btn-danger" href="<?php echo $this->url('deleteResource', array('id' => $resource['id']));   ?>"  ><i class="icon-remove icon-white"></i> delete</a>
                            </span>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true" style="display: none; height: 170px;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Delete resource</h4>
      </div>
      <div class="modal-body">
          Are you sure you want to delete resource ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a class="btn btn-danger" href=""><i class="icon-remove icon-white"></i> delete</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
