<div class="container">

    <?php echo $this->flashMessenger()->render(); ?>

    <h1>Scanned resources</h1>

    <br><br>

    <table class="table table-striped table-bordered table-sortable">
        <thead>
            <tr>
                <th>Controller</th>
                <th>Resource</th>
                <th class="filter-false sorter-false">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($resources as $resource) : ?>
                <tr>
                    <td><?php echo $resource['controller']; ?></td>
                    <td><a href="<?php echo $this->url('addResource', array('resource' => str_replace('route/', '', $resource['resource']))); ?>"><?php echo $resource['resource']; ?></a></td>
                    <td>
                        <div>
                            <a class="btn btn-success" href="<?php echo $this->url('addResource', array('resource' => str_replace('route/', '', $resource['resource']))); ?>"><i class="icon-edit icon-white"></i> add</a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>
